### ISSUE TITLE
Update needed?

### ISSUE THREAD

**Issue by russel** [WebFreak001/fontconfig-d#1]
I am guessing this D module was created using DStep. Although Fontconfig is very slow moving, I wonder if three years is too long to wait between updates? Perhaps an update is in order?

**Comment by WebFreak001** [comment]
oh yeah there was an upgrade from 2.12 to 2.13

DStep (or some other tool, I don't really remember anymore) was used for the initial conversion but new changes should be added manually now.

Just a few additions have been made, if you don't need
`FcDirCacheCreateUUID`,
`FcDirCacheDeleteUUID`,
`FcConfigFileInfoIterInit`,
`FcConfigFileInfoIterNext`,
`FcConfigFileInfoIterGet`,
`FcFreeTypeQueryAll`,
`FcPatternObjectCount`,
`FcPatternGetWithBinding`,
`FcPatternIterStart`,
`FcPatternIterNext`,
`FcPatternIterEqual`,
`FcPatternFindIter`,
`FcPatternIterIsValid`,
`FcPatternIterGetObject`,
`FcPatternIterValueCount`,
`FcPatternIterGetValue`,
`FcWeightFromOpenTypeDouble`,
`FcWeightToOpenTypeDouble`,
`FcStrBuildFilename` or
`FcConfigParseAndLoadFromMemory`

then you can use the current version with no problems too.
